import { hasUsableTranscript } from "@/lib/interview-report-gate";

export const DEFAULT_TRANSCRIPT_SUMMARY_THRESHOLD = 30;
export const DEFAULT_RAW_TAIL_LINES = 50;

function truncate(s: string, max: number): string {
  if (s.length <= max) return s;
  return `${s.slice(0, max)}\n\n[…truncated for length…]`;
}

export function formatQuestionScoresForReport(
  questionScores: { question: string; category?: string; score: number; notes?: string }[]
): string {
  return questionScores
    .map(
      (s) =>
        `- [${s.category || "general"}] ${s.score}/10 — ${s.question}${s.notes ? ` (interviewer note: ${s.notes})` : ""}`
    )
    .join("\n");
}

export type SpokenSectionInput = {
  transcriptLines: { speaker: string; text: string }[];
  clientProvidedSummary?: string;
  transcriptSummaryText?: string;
  transcriptSummaryError?: string | null;
  summaryThreshold?: number;
  rawTailLines?: number;
};

/**
 * Builds the spoken-transcript block for the interview report prompt.
 * Short transcripts stay verbatim; long ones use summary + tail (or fallback on error).
 */
export function buildSpokenSectionForReport(input: SpokenSectionInput): string {
  const threshold = input.summaryThreshold ?? DEFAULT_TRANSCRIPT_SUMMARY_THRESHOLD;
  const rawTail = input.rawTailLines ?? DEFAULT_RAW_TAIL_LINES;
  const transcriptLines = input.transcriptLines ?? [];

  if (!hasUsableTranscript(transcriptLines)) {
    return "(no spoken transcript captured — use INTERVIEWER SESSION NOTES below for verbal discussion context)";
  }

  const transcriptSummaryText = (input.clientProvidedSummary ?? input.transcriptSummaryText ?? "").trim();
  const transcriptTailLines = transcriptLines.slice(-rawTail);
  const transcriptTailBlock = transcriptTailLines.map((t) => `${t.speaker}: ${t.text}`).join("\n");
  const tailCoversAll =
    transcriptLines.length > 0 && transcriptTailLines.length === transcriptLines.length;

  if (transcriptSummaryText && !tailCoversAll) {
    return `### Structured summary (preferred — generated by a dedicated summarization agent over the full transcript):
${transcriptSummaryText}

### Raw transcript tail (last ${transcriptTailLines.length} lines, for direct evidence quoting):
${truncate(transcriptTailBlock, 30_000)}`;
  }

  if (input.transcriptSummaryError) {
    return `(summarization unavailable: ${input.transcriptSummaryError} — falling back to raw transcript tail)
${truncate(transcriptTailBlock, 60_000)}`;
  }

  if (transcriptLines.length > threshold) {
    // Long transcript but no summary yet — caller should summarize first; degrade to tail.
    return truncate(transcriptTailBlock, 60_000);
  }

  return truncate(transcriptTailBlock, 60_000);
}

export function shouldSummarizeTranscriptBeforeReport(
  transcriptLines: { text?: string }[],
  clientProvidedSummary?: string,
  threshold = DEFAULT_TRANSCRIPT_SUMMARY_THRESHOLD
): boolean {
  const summary = (clientProvidedSummary ?? "").trim();
  return !summary && hasUsableTranscript(transcriptLines) && transcriptLines.length > threshold;
}
